In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import random
import pickle
import pandas as pd
from tensorflow.keras.utils import to_categorical

In [2]:
#data path
DATADIR = "C:/Users/Aaron/__ANPR_THESIS/train" #train dataset folder
DATADIR2 = "C:/Users/Aaron/__ANPR_THESIS/test" #test dataset folder

#classes
CATEGORIES = ["LicensePlateN","LicensePlateO"] #total of 36 classes [0-9][A-Z]
# CATEGORIES = ["LicensePlateN"] #total of 36 classes [0-9][A-Z]
IMG_SIZE = 64

In [3]:
#labels
train_x = []
train_y = []

test_x = []
test_y = []

In [4]:
# Preparing zero-valued Numpy array for cut objects
# Shape: image number, height, width, number of channels
train_x = np.zeros((1, 64, 64, 3))
test_x = np.zeros((1, 64, 64, 3))


# Preparing zero-valued Numpy array for classes' numbers
# Shape: class's number
train_y = np.zeros(1)
test_y = np.zeros(1)


# Preparing temp zero-valued Numpy array for current cut object
# Shape: image number, height, width, number of channels
x_temp = np.zeros((1, 64, 64, 3))



# Preparing temp zero-valued Numpy array for class's number
# Shape: class's number
y_temp = np.zeros(1)


# Defining boolean variable to track arrays' shapes

In [8]:
first_object = True
#for accessing each folder

#training data


training_data = []


for category in CATEGORIES:
    path = os.path.join(DATADIR, category) #path to categories
    class_num = CATEGORIES.index(category)
    A_path = (path + '/' + 'Annotations') 
    for img in os.listdir(path):
        if img == 'Annotations':
            continue
            
        img_array = cv2.imread(os.path.join(path,img), cv2.COLOR_BGR2RGB) #convert images to greyscale

        #For Images that need to be segmented 
        '''
        a = pd.read_csv((A_path + '/' + img[:-4] + '.txt'),
        header=None,
        delim_whitespace=True)
        # Getting number of rows and columns from current Pandas dataFrame
        a_rows = a.shape[0]
        a_columns = a.shape[1]

        # Defining variable for current class's name
        class_name = ''

        # Getting class's name from current Pandas dataFrame
        # Assembling complex name if it consists of few words
        for i in range(a_columns - 4):
            class_name += a.loc[0, i]

            # Adding space at the end
            class_name += ' '

        # Deleting space at the end
        class_name = class_name.rstrip(' ')

        # Getting index of class's name
        # according to its order in the list 'labels'
        class_index = class_num

        # Preparing index to start reading coordinates of objects from
        ii = a_columns - 4

        # Iterating all rows from current Pandas dataFrame
        for i in range(a_rows):
            # Getting coordinates of current object
            # Making numbers as integers
            x_min = int(a.loc[i, ii])
            y_min = int(a.loc[i, ii + 1])
            x_max = int(a.loc[i, ii + 2])
            y_max = int(a.loc[i, ii + 3])
            #print (x_min, y_min, x_max, y_max)
            
            # Cutting object from entire image
            cut_object = img_array[y_min:y_max, x_min:x_max]
            

            # Resizing cut object to 100 by 100 pixels size
            cut_object = cv2.resize(cut_object,
                                    (64, 64),
                                    interpolation=cv2.INTER_CUBIC)
            #print(cut_object)

            # Checking if it is the first object
            if first_object:
                # Assigning to the first position first object
                train_x[0, :, :, :] = cut_object

                # Assigning to the first position its class index
                train_y[0] = class_index

                # Changing boolean variable
                first_object = False

            # Collecting next objects into temp arrays
            # Concatenating arrays vertically
            else:
                # Assigning to temp array current object
                x_temp[0, :, :, :] = cut_object

                # Assigning to temp array its class index
                y_temp[0] = class_index

                # Concatenating vertically temp arrays to main arrays
                train_x = np.concatenate((train_x, x_temp), axis=0)
                train_y = np.concatenate((train_y, y_temp), axis=0) 
                '''               
        new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE)) #resizing images to 50x50
        training_data.append([new_array, class_num])

             


#testing data
testing_data = []

for category in CATEGORIES:
    path = os.path.join(DATADIR2, category) #path to categories
    class_num = CATEGORIES.index(category)
    A_path = (path + '/' + 'Annotations') 
    for img in os.listdir(path):
        if img == 'Annotations':
            continue

        img_array = cv2.imread(os.path.join(path,img), cv2.COLOR_BGR2RGB) #convert images to greyscale

        #For images that need to be segmented
        '''
        a = pd.read_csv((A_path + '/' + img[:-4] + '.txt'),
        header=None,
        delim_whitespace=True)
        # Getting number of rows and columns from current Pandas dataFrame
        a_rows = a.shape[0]
        a_columns = a.shape[1]

        # Defining variable for current class's name
        class_name = ''

        # Getting class's name from current Pandas dataFrame
        # Assembling complex name if it consists of few words
        for i in range(a_columns - 4):
            class_name += a.loc[0, i]

            # Adding space at the end
            class_name += ' '

        # Deleting space at the end
        class_name = class_name.rstrip(' ')

        # Getting index of class's name
        # according to its order in the list 'labels'
        class_index = class_num

        # Preparing index to start reading coordinates of objects from
        ii = a_columns - 4

        # Iterating all rows from current Pandas dataFrame
        for i in range(a_rows):
            # Getting coordinates of current object
            # Making numbers as integers
            x_min = int(a.loc[i, ii])
            y_min = int(a.loc[i, ii + 1])
            x_max = int(a.loc[i, ii + 2])
            y_max = int(a.loc[i, ii + 3])
            
            # Cutting object from entire image
            cut_object = img_array[y_min:y_max, x_min:x_max]
            

            # Resizing cut object to 100 by 100 pixels size
            cut_object = cv2.resize(cut_object,
                                    (64, 64),
                                    interpolation=cv2.INTER_CUBIC)
            
            # Checking if it is the first object
            if first_object:
                # Assigning to the first position first object
                train_x[0, :, :, :] = cut_object
                
                # Assigning to the first position its class index
                train_y[0] = class_index

                # Changing boolean variable
                first_object = False


            # Collecting next objects into temp arrays
            # Concatenating arrays vertically
            else:
                # Assigning to temp array current object
                x_temp[0, :, :, :] = cut_object
                

                # Assigning to temp array its class index
                y_temp[0] = class_index

                # Concatenating vertically temp arrays to main arrays
                test_x = np.concatenate((test_x, x_temp), axis=0)
                test_y = np.concatenate((test_y, y_temp), axis=0)
        '''    
        new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
        testing_data.append([new_array, class_num])


[[[[ 18.  15.  39.]
   [101.  98. 121.]
   [137. 134. 151.]
   ...
   [ 21.  18.  42.]
   [ 21.  18.  41.]
   [ 22.  19.  42.]]

  [[ 24.  22.  44.]
   [138. 136. 150.]
   [122. 119. 132.]
   ...
   [ 17.  14.  36.]
   [ 16.  14.  34.]
   [ 22.  19.  42.]]

  [[106. 105. 122.]
   [ 19.  19.  27.]
   [ 37.  35.  43.]
   ...
   [ 52.  52.  62.]
   [ 17.  16.  27.]
   [ 22.  18.  42.]]

  ...

  [[ 31.  30.  28.]
   [ 32.  30.  29.]
   [ 34.  33.  31.]
   ...
   [ 32.  30.  29.]
   [ 32.  31.  29.]
   [ 16.  15.  14.]]

  [[ 31.  30.  28.]
   [ 32.  30.  29.]
   [ 33.  31.  30.]
   ...
   [ 31.  30.  28.]
   [ 14.  13.  12.]
   [ 16.  15.  15.]]

  [[ 29.  28.  26.]
   [ 30.  29.  27.]
   [ 31.  30.  28.]
   ...
   [ 11.   9.   8.]
   [ 14.  13.  12.]
   [ 17.  15.  15.]]]


 [[[172. 173. 171.]
   [178. 179. 177.]
   [178. 176. 176.]
   ...
   [221. 213. 213.]
   [103.  96.  96.]
   [230. 228. 227.]]

  [[178. 179. 177.]
   [226. 221. 222.]
   [218. 213. 214.]
   ...
   [ 47.  43.  48.]
 

In [9]:
from sklearn.utils import shuffle
#print(testing_data)
#print(training_data)
train_x, train_y = shuffle(train_x, train_y)
print(train_x.shape)
print(train_y.shape)
print()

(10, 64, 64, 3)
(10,)



In [6]:
for features, label in training_data: 
    train_x.append(features)
    train_y.append(label)

train_x = np.array(train_x).reshape(-1, IMG_SIZE, IMG_SIZE, 3) #1 is grayscale
train_y = np.array(train_y).reshape(-1)


for features, label in testing_data:
    test_x.append(features)
    test_y.append(label)
test_x = np.array(test_x).reshape(-1, IMG_SIZE, IMG_SIZE, 3) #1 is grayscale
test_y = np.array(test_y).reshape(-1)


In [7]:
#for training data there are 1000+ images dimensions are 28x28x1
#for testing data there are 600+ images dimensions are 28x28x1

print('Training data shape : ', train_x.shape, train_y.shape)
print('Testing data shape : ', test_x.shape, test_y.shape)


Training data shape :  (10, 100, 100, 3) (10,)
Testing data shape :  (10, 100, 100, 3) (10,)


In [8]:
# Find the unique numbers from the train labels

classes = np.unique(train_y)
nClasses = len(classes)
print('Total number of outputs : ', nClasses)
print('Output classes : ', classes)

Total number of outputs :  2
Output classes :  [0 1]


In [ ]:
plt.figure(figsize=[5,5])

# Display the first image in training data
plt.subplot(121)
plt.imshow(train_x[143,:,:], cmap='gray')
plt.title("Ground Truth (training): {}".format(train_y[153]))

# Display the first image in testing data
plt.subplot(122)
plt.imshow(test_x[143,:,:], cmap='gray')
plt.title("Ground Truth (testing): {}".format(test_y[191]))

#3. DATA PREPROCESSING --------------------

In [ ]:
#convert int8 -> float32 format
train_x = train_x.astype('float32')
test_x = test_x.astype('float32')

train_x = train_x / 255.

test_x = test_x / 255.

In [ ]:
# Change the labels from categorical -> one-hot encoding
train_y_one_hot = to_categorical(train_y)
test_y_one_hot = to_categorical(test_y)

# Display the change for category label using one-hot encoding
print('Original label:', train_y[0])
print('After conversion to one-hot:', train_y_one_hot[0])



In [ ]:
#split dataset into training and validation set
#20% of the training and validation dataset are not being trained to avoid overfitting; will help boost the test performance

from sklearn.model_selection import train_test_split
train_x,valid_x,train_label,valid_label = train_test_split(train_x, train_y_one_hot, train_size=0.2, random_state=13)

In [ ]:
#checking the shape of training and validation set after splitting dataset
train_x.shape, valid_x.shape, train_label.shape, valid_label.shape

#222- TRAINING
#889 - VALIDATION
# = 1111

In [ ]:

mean_rgb_dataset_custom =  np.mean(train_x, axis=0)
x_train_255_mean = train_x - mean_rgb_dataset_custom
x_validation_255_mean = valid_x - mean_rgb_dataset_custom
x_test_255_mean = test_x_ - mean_rgb_dataset_custom

In [ ]:
#MODEL THE DATA

import keras
from tensorflow import keras
from keras.models import Sequential,Model
from tensorflow.python.keras.models import Input
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import LeakyReLU
from keras.layers.core import Lambda
import h5py

In [ ]:
batch_size = 64
epochs = 50
num_classes = 2

#Batch size = number of training examples utilized in one iteration.
#no of epochs: As the number of epochs increases, 
#more number of times the weight are changed in the neural network 
#and the curve goes from underfitting to optimal to overfitting curve.


#5. NEURAL NETWORK ARCHITECTURE-------------------------
# CONV2D, RELU, MAXPOOLING2D, DROPOUT, FLATTEN, DENSE

In [ ]:
#with dropout

plate_model = Sequential()

plate_model.add(Lambda(lambda x: x / 255. - .5,input_shape=(100,100,3), name='norm'))
#first convolution layer 32-3x3 filter ------------------------
plate_model.add(Conv2D(32, kernel_size=(3, 3),activation='linear',padding='same',input_shape=(100,100,3)))
plate_model.add(LeakyReLU(alpha=0.1))
#max pooling 2x2
plate_model.add(MaxPooling2D((2, 2),padding='same'))
#adding dropout for overfitting
plate_model.add(Dropout(0.25))

#second convolution layer 64-3x3 filter ---------------------- 
plate_model.add(Conv2D(64, (3, 3), activation='linear',padding='same'))
plate_model.add(LeakyReLU(alpha=0.1))
plate_model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
plate_model.add(Dropout(0.25))

#second convolution layer 128-3x3 filter ---------------------- 
plate_model.add(Conv2D(128, (3, 3), activation='linear',padding='same'))
plate_model.add(LeakyReLU(alpha=0.1))                  
plate_model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
plate_model.add(Dropout(0.4))
#adding flatten layer
plate_model.add(Flatten())
plate_model.add(LeakyReLU(alpha=0.1))           
plate_model.add(Dropout(0.3))
#adding dense layer
plate_model.add(Dense(2, activation='softmax'))
# class

#total of 16 added layers

In [ ]:
#output layer 
plate_model.compile(loss = keras.losses.categorical_crossentropy, 
                    optimizer = keras.optimizers.Adam(), #compile the model using adam optimizer
                    metrics = ['accuracy'])

In [ ]:
#VISUALIZE THE LAYERS
plate_model.summary()

In [ ]:
plate_train = plate_model.fit(train_x, train_label, 
                                  batch_size=batch_size,
                                  epochs=epochs,
                                  verbose=1,
                                  validation_data=(valid_x, valid_label))

#shows 50 epochs for training

In [ ]:
# # save the model
plate_model.save("License_Model.h5") #sample
with h5py.File('License_Model.h5', 'a') as f:
    # Calling methods to create datasets of given shapes and types
    # Saving Numpy arrays for training
    f.create_dataset('x_train', data=train_x, dtype='f')
    f.create_dataset('y_train', data=train_label, dtype='i')

    # Saving Numpy arrays for validation
    f.create_dataset('x_validation', data=valid_x, dtype='f')
    f.create_dataset('y_validation', data=valid_label, dtype='i')

    # Saving Numpy arrays for testing
    f.create_dataset('x_test', data=test_x, dtype='f')
    f.create_dataset('y_test', data=test_y_one_hot, dtype='i')


#plate_model.save_weights("greycar_dropout.hdf5") #sample

In [ ]:
test_eval = plate_model.evaluate(test_x, test_y_one_hot, verbose=1)
#shows the test loss and accuracy 
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

In [ ]:
# plot the accuracy and loss points
#shows graph of training and validation accuracy 
#shows graph of training and validation loss

accuracy = plate_train.history['accuracy']
val_accuracy = plate_train.history['val_accuracy']
loss = plate_train.history['loss']
val_loss = plate_train.history['val_loss']

epochs = range(len(accuracy))
plt.plot(epochs, accuracy, 'bo', label='Training accuracy')
plt.plot(epochs, val_accuracy, 'b', label='Validation accuracy')

plt.title('Training and validation accuracy')
plt.legend()
plt.figure()
plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()
plt.show()


#result: validation loss and validation accuracy both are in sync with the training loss and training accuracy. 
# Even though the validation loss and accuracy line are not linear, 
#but it shows that your model is not overfitting: the validation loss is decreasing and 
#not increasing, and there is not much gap between training and validation accuracy.


In [ ]:
predicted_classes = plate_model.predict(test_x)

In [ ]:
predicted_classes = np.argmax(np.round(predicted_classes),axis=1)

In [ ]:
predicted_classes.shape, test_y.shape

In [ ]:
# FOUND CORRECT LABELS
correct = np.where(predicted_classes==test_y)[0]
print("Found correct labels")
for i, correct in enumerate(correct[:9]):
    plt.subplot(3,3,i+1)
    plt.imshow(test_x[correct].reshape(100,100), cmap='gray', interpolation='none')
    plt.title("Predicted {}, Class {}".format(predicted_classes[correct], test_y[correct]))
    plt.tight_layout()

In [ ]:
#FOUND INCORRECT LABELS

incorrect = np.where(predicted_classes!=test_y)[0]
print("Found incorrect labels")
for i, incorrect in enumerate(incorrect[:9]):
    plt.subplot(3,3,i+1)
    plt.imshow(test_x[incorrect].reshape(100,100), cmap='gray', interpolation='none')
    plt.title("Predicted {}, Class {}".format(predicted_classes[incorrect], test_y[incorrect]))
    plt.tight_layout()
    
#RESULTS: make sense because training accuracy is only about 89% 

#10. CLASSIFICATION REPORT -----------------------
#for identifying the misclassified classes in more detail.